# Generated by Django 5.2.6 on 2025-10-14 20:05

from django.db import migrations
from django.utils import timezone


def seed_questions(apps, schema_editor):
    Question = apps.get_model("polls", "Question")
    Choice = apps.get_model("polls", "Choice")

    # Only seed if no questions exist
    if Question.objects.exists():
        return

    # Question 1
    q1 = Question.objects.create(
        question_text="What's up?",
        pub_date=timezone.now()
    )
    Choice.objects.create(question=q1, choice_text="Not much", votes=0)
    Choice.objects.create(question=q1, choice_text="The sky", votes=0)
    Choice.objects.create(question=q1, choice_text="Just chilling", votes=0)

    # Question 2
    q2 = Question.objects.create(
        question_text="What's your favorite programming language?",
        pub_date=timezone.now()
    )
    Choice.objects.create(question=q2, choice_text="Python", votes=0)
    Choice.objects.create(question=q2, choice_text="JavaScript", votes=0)
    Choice.objects.create(question=q2, choice_text="Java", votes=0)

    # Question 3
    q3 = Question.objects.create(
        question_text="Which framework do you prefer?",
        pub_date=timezone.now()
    )
    Choice.objects.create(question=q3, choice_text="Django", votes=0)
    Choice.objects.create(question=q3, choice_text="Flask", votes=0)
    Choice.objects.create(question=q3, choice_text="FastAPI", votes=0)

    # Question 4
    q4 = Question.objects.create(
        question_text="What's the best database for web apps?",
        pub_date=timezone.now()
    )
    Choice.objects.create(question=q4, choice_text="PostgreSQL", votes=0)
    Choice.objects.create(question=q4, choice_text="MySQL", votes=0)
    Choice.objects.create(question=q4, choice_text="SQLite", votes=0)


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_questions),
    ]
